jasypt:
  encryptor:
    bean: jasyptStringEncryptor
spring:
  datasource:
    url: ENC(G1FkoKhv0FR/nyT2pgNgM+mf457KKdqMqenE3sB+IWguMRcntq73pnzCc4LuMbKjbJENJL+vQZEIisGEQBiBAwOZu0jf7K7DnnBdRtq/HJsFTuLThJm4Lix/Tyg6wseaRk8ja/yhAyL22pmPkQEbuQ==)
    username: ENC(AoE2hwRWKMqIVKzMMIVebg==)
    password: ENC(RK5W4na3nfatvtrIfk4W+Pva/NJBaFDH)
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health
      path-mapping:
        health: health_check
security:
  jwt:
    token:
      secret-key: ENC(+OE50rHWSUDc/cQYOwCfRIWKX+8yd3QKRpee4oshFBBXjvitpbh8t4oqQ7NrDuQECLNxeCGXP5T5LnHl3hjjFQ==)
      expire-length: ENC(wlpSC8pyEY7BI94TCfMFnQ==)
