jasypt:
  encryptor:
    bean: jasyptStringEncryptor
spring:
  logging:
    level:
      root: DEBUG
  datasource:
    url: ENC(Cl8Hw6kPWh6JzdmVP4Qu7+QUujAsha5ayM0GlMU9oLUPBHgC3eQurPjuWfzZ1H1ug1ld265MDNg=)
    username: ENC(wyQabgNCGOH9F8YoPVxemQ==)
    password: ENC(fVnOv3jJfBlC5uzrhQBGQQ==)
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
security:
  jwt:
    token:
      secret-key: ENC(+OE50rHWSUDc/cQYOwCfRIWKX+8yd3QKRpee4oshFBBXjvitpbh8t4oqQ7NrDuQECLNxeCGXP5T5LnHl3hjjFQ==)
      expire-length: ENC(wlpSC8pyEY7BI94TCfMFnQ==)