jasypt:
  encryptor:
    bean: jasyptStringEncryptor
spring:
  datasource:
    url: ENC(r4r+G75p/uhs4EyvkbLeEPGxu3S5s3xHC6UOhelVcaLWz2sfK4xOVnW4WGAvZ9ktMQlh8tiTWug=)
    username: ENC(mxu1mEz1w9vwoCB/qGaPYw==)
    password: ENC(XW8YGEX8+GpLgi7bM+/I/bYDAk7Se7H5)
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always